FROM node:22.14.0-bookworm

# 建立工作目錄
RUN mkdir /app
WORKDIR /app

# 複製 Next.js 應用程式的檔案到容器中
COPY ./nextjs/ /app/

# 安裝依賴並編譯 Next.js 應用
RUN npm install && \
    npm run build

# 靜態檔案複製到 /static
RUN mkdir /static
RUN cp -r /app/out/* /static