x-default-opts: &default-opts
  restart: always               # always restart the container unless stopped manually
  tty: true                     # allocate a pseudo-TTY
  stdin_open: true              # keep stdin open
  privileged: false             # to avoid host kernel sharing
  ipc: private                  # to avoid IPC namespace sharing with the host

services:
  fastapi:                      # FastAPI service configuration
    build:
      context: .                # Build context is the current directory
      dockerfile: dockerfile.fastapi # Use the specified Dockerfile
    container_name: ai_server_sample_fastapi
    <<: *default-opts
    volumes:
      - ./fastapi:/app          # Mount a volume for FastAPI data
    networks:
      - server_network
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "Starting FastAPI server..."
        chmod +x entrypoint.sh
        ./entrypoint.sh

  nextjs:
    image: node:22.14.0-bookworm
    container_name: ai_server_sample_nextjs
    <<: *default-opts
    volumes:
      - ./nextjs:/app            # Mount a volume for Next.js data
    networks:
      - server_network
    entrypoint: /bin/sh -c "cd /app && npm install && npm run dev"

  nginx:
    image: nginx:stable-perl     # Use the latest Nginx image
    container_name: ai_server_sample_nginx
    <<: *default-opts
    ports:
      - ${NGINX_PORT}:80         # Expose port 80 for HTTP traffic
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi                  # Ensure FastAPI is started before Nginx
      - nextjs                   # Ensure Next.js is started before Nginx
    networks:
      - server_network

networks:
  server_network:               # Network for server communication
    driver: bridge              # Use the bridge network driver