x-default-opts: &default-opts
  restart: always               # always restart the container unless stopped manually
  tty: true                     # allocate a pseudo-TTY
  stdin_open: true              # keep stdin open
  privileged: false             # to avoid host kernel sharing
  ipc: private                  # to avoid IPC namespace sharing with the host

x-web-opts: &web-opts
  restart: no                   # do not restart the container automatically
  tty: true                     # allocate a pseudo-TTY
  stdin_open: true              # keep stdin open
  privileged: false             # to avoid host kernel sharing
  ipc: private                  # to avoid IPC namespace sharing with the host

services:
  fastapi:                      # FastAPI service configuration
    build:
      context: .                # Build context is the current directory
      dockerfile: dockerfile.fastapi # Use the specified Dockerfile
    container_name: ai_server_sample_fastapi
    <<: *default-opts
    networks:
      - server_network
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "Starting FastAPI server..."
        chmod +x entrypoint.sh
        ./entrypoint.sh

  nextjs:
    build:
      context: .                # Build context is the current directory
      dockerfile: dockerfile.nextjs # Use the specified Dockerfile for Next.js
    container_name: ai_server_sample_nextjs
    <<: *web-opts
    volumes:
      - static_files:/app/out
    networks:
      - server_network
    entrypoint:
      - /bin/sh
      - -c
      - |
        cd /app
        npm install
        npm run build

  nginx:
    build: 
      context: .
      dockerfile: dockerfile.nginx # Use the specified Dockerfile for Nginx
    container_name: ai_server_sample_nginx
    <<: *default-opts
    ports:
      - ${NGINX_PORT}:80         # Expose port 80 for HTTP traffic
    volumes:
      - static_files:/static
    depends_on:
      - fastapi                  # Ensure FastAPI is started before Nginx
      - nextjs                   # Ensure Next.js is started before Nginx
    networks:
      - server_network

networks:
  server_network:               # Network for server communication
    driver: bridge              # Use the bridge network driver
    
volumes:
  static_files: {}