x-default-opts: &default-opts
  restart: always
  tty: true
  stdin_open: true
  privileged: false
  ipc: private
services:
  fastapi:
    build:
      context: ../
      dockerfile: dockerfile/dockerfile.fastapi
    container_name: ai_server_sample_fastapi
    <<: *default-opts
    networks:
      - server_network
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "Starting FastAPI server..."
        chmod +x entrypoint.sh
        ./entrypoint.sh

  nextjs:
    build:
      context: ../
      dockerfile: dockerfile/dockerfile.nextjs
    container_name: ai_server_sample_nextjs
    <<: *default-opts
    volumes:
      - static_files:/static
    networks:
      - server_network
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Copy Next.js Static..."
        rm -rf /static/*
        cp -r /app/out/* /static
        tail -f /dev/null

  nginx:
    build: 
      context: ../
      dockerfile: dockerfile/dockerfile.nginx
    container_name: ai_server_sample_nginx
    <<: *default-opts
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_files:/static
    depends_on:
      - fastapi
      - nextjs
    networks:
      - server_network

networks:
  server_network:
    driver: bridge
    
volumes:
  static_files: {}