x-default-opts: &default-opts
  restart: always
  tty: true
  stdin_open: true
  privileged: false
  ipc: private

services:
  fastapi:
    build:
      context: ../
      dockerfile: dockerfile/dockerfile.fastapi
    container_name: ai_server_sample_fastapi
    <<: *default-opts
    volumes:
      - ../fastapi:/app
    networks:
      - server_network
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "Starting FastAPI server..."
        chmod +x entrypoint.sh
        ./entrypoint.sh

  nextjs:
    image: node:22.14.0-bookworm
    container_name: ai_server_sample_nextjs
    <<: *default-opts
    volumes:
      - ../nextjs:/app
    networks:
      - server_network
    entrypoint: /bin/sh -c "cd /app && npm install && npm run dev"

  nginx:
    image: nginx:stable-perl
    container_name: ai_server_sample_nginx
    <<: *default-opts
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
      - nextjs
    networks:
      - server_network

networks:
  server_network:
    driver: bridge